version: '2'

services:
  web:
    image: mazurik
    depends_on:
      - postgres
      - redis
    build: .
    command: bash -c "cd /mazurik_blog && bundle exec rails server -p 3000 -b 0.0.0.0"
    links:
      - postgres
      - redis
    volumes:
      - .:/mazurik_blog
    ports:
      - 3000:3000

  postgres:
    image: postgres:9.6.2
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5433:5432
    volumes:
       - postgres_database:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    expose:
      - 6379
    volumes:
      - redis_database:/var/lib/redis/data

  sidekiq:
    image: mazurik
    command: bash -c "cd /mazurik_blog && bundle exec sidekiq -q recommendable"
    links:
      - postgres
      - redis
    volumes:
      - .:/mazurik_blog

volumes:
  redis_database:
  postgres_database:
