version: '2'
services:

  web:
    image: mazurik_blog
    build: .
    command: bash -c "cd /mazurik_blog && bundle exec rails server -p 3000 -b 0.0.0.0"
    volumes:
      - .:/mazurik_blog
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    image: postgres:9.6.2
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
    volumes:
       - ./container_data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./container_data/redis:/var/lib/redis/data

  sidekiq:
    image: mazurik_blog
    command: bash -c "cd /mazurik_blog && bundle exec sidekiq -q recommendable"
    links:
      - postgres
      - redis
    volumes:
      - .:/mazurik_blog

volumes:
  redis:
  postgres:
