default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: postgres
  port: 5432
  pool: 30

development:
  <<: *default
  database: mazurik_blog_development

test:
  <<: *default
  database: mazurik_blog_test

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  username: postgres
  database: mazurik_blog_production
  password: password
