default: &default
  adapter: postgresql
  encoding: unicode
  username: alekseymazurik
  port: 5432
  pool: 5

development:
  <<: *default
  database: mazurik_blog_development

test:
  <<: *default
  database: mazurik_blog_test

production:
  <<: *default
  database: postgres
  password: password
