default: &default
 adapter: postgresql
 encoding: unicode
 pool: 30
 username: postgres
 password: postgres

development:
 <<: *default
 database: mazurik_development
 host: postgres

test:
 <<: *default
 database: mazurik_test
 host: postgres

production:
 <<: *default
 database: mazurik_production
