default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  database: mazurik_blog_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: mazurik_blog_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  username: postgres
  database: mazurik_blog_production
  password: password
